package com.br.emanuelap.geojsonproject.enums;


public enum TrechoDrenagemEnums {


  CORREDEIRA, QEBRADAGUA, BARRAGEM, PONTODRENAGEM, TRECHOMASSADAGUA, TRECHOCURSODAGUA, MASSADAGUA, AREAUMIDA, TERRENOSUJEITOAINUNDACAO


}
